### PR TITLE
lug: elan update

### PR DESCRIPTION
**Pull request by timechess**

### CODE REVIEW

**Comment by PhotonQuantum** [comment]
Please run `make caddy-gen` to update `Caddyfile`.

**Comment by timechess** [comment]
Done. @PhotonQuantum

**Comment by PhotonQuantum** [comment]
Sorry, could you please rebase your branch to solve the conflict? You may want to run `make caddy-gen` again to generate the config file.

**Comment by timechess** [comment]
I think it will be OK this time. @PhotonQuantum

**Comment by PhotonQuantum** [comment]
I noticed that there isn't any document available for Lean repositories. Would you be interested in contributing one?

**Comment by timechess** [comment]
Sorry for overlooking the message. I'm happy to do that. Is this https://github.com/sjtug/portal the right place?

**Comment by PhotonQuantum** [comment]
> Is this https://github.com/sjtug/portal the right place?

Yes! Please commit to the mirror-help folder with the same name as the repo.

**Comment by timechess** [comment]
I notice there is already a `elan.md` by @alissa-tung . Why it is not displayed?

**Comment by timechess** [comment]
It seems that there is an error in format. I'll update the doc later.

**Pull request merged**
