### PR TITLE
fix: more retain elan versions

### PR DESCRIPTION
**Pull request by alissa-tung**

### CODE REVIEW

**Comment by alissa-tung** [comment]
Hello @PhotonQuantum , this merge request set `--retain-elan-versions` to 5, since elan is releasing beta release and we hope normal user can still use the stable ones

**Comment by alissa-tung** [comment]
@PhotonQuantum @timechess would you have time help me fix the Caddy files?

**Comment by PhotonQuantum** [comment]
> @PhotonQuantum @timechess would you have time help me fix the Caddy files?

You can do this by `make caddy-gen`.

**Comment by alissa-tung** [comment]
> > @PhotonQuantum @timechess would you have time help me fix the Caddy files?
> 
> You can do this by `make caddy-gen`.

Does not cause changes and CI says


```
Creating mirror-docker-unified_caddy_run ... 
Creating mirror-docker-unified_caddy_run ... done
{"level":"info","ts":1719225404.709176,"msg":"using config from file","file":"/etc/caddy/Caddyfile.siyuan"}
Error: ambiguous config file format; please specify adapter (use --adapter)
1
make: *** [Makefile:5: caddy-verify-config] Error 1
```

cc @PhotonQuantum

**Comment by PhotonQuantum** [comment]
Oh sorry our ci broke, I'll merge your pr manually.

**Pull request merged**
